-- Create metrics table
CREATE TABLE metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    unit VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create unique index on metric name
CREATE UNIQUE INDEX uk_metric_name ON metrics(name);

-- Insert default metrics
INSERT INTO metrics (name, unit) VALUES
    ('temperature', 'celsius'),
    ('humidity', 'percentage'),
    ('wind_speed', 'km/h');