-- Create sensor_readings table
CREATE TABLE sensor_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id VARCHAR(100) NOT NULL,
    metric_id BIGINT NOT NULL,
    metric_value NUMERIC(10, 4) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reading_metric FOREIGN KEY (metric_id) REFERENCES metrics(id)
);

-- Create indexes for common query patterns
CREATE INDEX idx_sensor_id_timestamp ON sensor_readings(sensor_id, timestamp);
CREATE INDEX idx_metric_id_timestamp ON sensor_readings(metric_id, timestamp);
CREATE INDEX idx_timestamp ON sensor_readings(timestamp);
